stages:
  - build
  - deploy

build dev:
  image: node:12
  stage: build
  only:
    - dev
  script:
    - npm install -g @vue/cli@latest
    - npm install
    - npm run lint
    - npm run build
  artifacts:
    paths:
      # Build folder
      - dist/
    expire_in: 1 hour

deploy dev:
  image: python:latest
  stage: deploy
  only:
    - dev
  script:
    - pip install awscli
    - aws s3 sync ./dist s3://ac-cicd-test/dev
